### ISSUE TITLE
Deprecation warning: moment().subtract(period, number) is deprecated. 

### ISSUE THREAD

**Issue by dreftymac** [leonardosantos/momentjs-business#2]
Please use moment().subtract(number, period) instead.

```
  if (true!=0) {
    var date_beg = moment('2014-10-01');    
    var date_end = moment('2014-11-01');
    console.log( 'date businessDiff in days', date_end.businessDiff(date_beg) );    
  }
```

**Comment by cphelefu** [comment]
You can fix this with a find and replace. Look at this link for details;

http://www.phronesisweb.com/blog/deprecation-warning-moment-subtractperiod-number-is-deprecated-please-use-moment-subtractnumber-period-fixing-this-in-visual-studio/

This is more focused on MS Visual Studio but it should work for any reliable IDE.
